# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\opps\Desktop\GUI_test\mainGUI_alpha.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 623)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.software_group = QtWidgets.QGroupBox(self.centralwidget)
        self.software_group.setGeometry(QtCore.QRect(10, 79, 551, 121))
        self.software_group.setTitle("")
        self.software_group.setObjectName("software_group")
        self.gridLayoutWidget = QtWidgets.QWidget(self.software_group)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 531, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.softwaregroup_grid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.softwaregroup_grid.setContentsMargins(0, 0, 0, 0)
        self.softwaregroup_grid.setObjectName("softwaregroup_grid")
        self.simu_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.simu_btn.setStyleSheet("QPushButton {background-color: #2eaf83;color: white;}")
        self.simu_btn.setObjectName("simu_btn")
        self.softwaregroup_grid.addWidget(self.simu_btn, 0, 2, 1, 1)
        self.exit_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.exit_btn.setStyleSheet("QPushButton {background-color: #1b4aa1;color: white;}")
        self.exit_btn.setObjectName("exit_btn")
        self.softwaregroup_grid.addWidget(self.exit_btn, 1, 2, 1, 1)
        self.save_data_box = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.save_data_box.setObjectName("save_data_box")
        self.softwaregroup_grid.addWidget(self.save_data_box, 1, 1, 1, 1)
        self.yes_or_no_hbox = QtWidgets.QHBoxLayout()
        self.yes_or_no_hbox.setObjectName("yes_or_no_hbox")
        self.yes_btn = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.yes_btn.setStyleSheet("font: 10pt \"Calibri\";")
        self.yes_btn.setObjectName("yes_btn")
        self.yes_or_no_hbox.addWidget(self.yes_btn)
        self.no_btn = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.no_btn.setStyleSheet("font: 10pt \"Calibri\";")
        self.no_btn.setObjectName("no_btn")
        self.yes_or_no_hbox.addWidget(self.no_btn)
        self.softwaregroup_grid.addLayout(self.yes_or_no_hbox, 2, 1, 1, 1)
        self.method_menu = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.method_menu.setObjectName("method_menu")
        self.method_menu.addItem("")
        self.method_menu.addItem("")
        self.method_menu.addItem("")
        self.method_menu.addItem("")
        self.method_menu.addItem("")
        self.method_menu.addItem("")
        self.softwaregroup_grid.addWidget(self.method_menu, 0, 0, 1, 1)
        self.save_fig_box = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.save_fig_box.setObjectName("save_fig_box")
        self.softwaregroup_grid.addWidget(self.save_fig_box, 0, 1, 1, 1)
        self.save_time_lab = QtWidgets.QLabel(self.gridLayoutWidget)
        self.save_time_lab.setStyleSheet("QLabel {\n"
"    font-family: \"SimSun\";\n"
"    font-size: 10pt;\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.save_time_lab.setObjectName("save_time_lab")
        self.softwaregroup_grid.addWidget(self.save_time_lab, 2, 0, 1, 1)
        self.para_group = QtWidgets.QGroupBox(self.centralwidget)
        self.para_group.setGeometry(QtCore.QRect(10, 210, 551, 371))
        self.para_group.setStyleSheet("QGroupBox {\n"
"    font-size: 10pt; \n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.para_group.setObjectName("para_group")
        self.time_group = QtWidgets.QGroupBox(self.para_group)
        self.time_group.setGeometry(QtCore.QRect(10, 20, 261, 161))
        self.time_group.setTitle("")
        self.time_group.setObjectName("time_group")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.time_group)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 241, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.timegroup_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.timegroup_grid.setContentsMargins(0, 0, 0, 0)
        self.timegroup_grid.setObjectName("timegroup_grid")
        self.sample_lab = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.sample_lab.setObjectName("sample_lab")
        self.timegroup_grid.addWidget(self.sample_lab, 1, 0, 1, 1)
        self.simu_lab = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.simu_lab.setObjectName("simu_lab")
        self.timegroup_grid.addWidget(self.simu_lab, 0, 0, 1, 1)
        self.init_lab = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.init_lab.setObjectName("init_lab")
        self.timegroup_grid.addWidget(self.init_lab, 2, 0, 1, 1)
        self.simu_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.simu_edit.setStyleSheet("QLineEdit {\n"
"    font: 10pt \"Times New Roman\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.simu_edit.setObjectName("simu_edit")
        self.timegroup_grid.addWidget(self.simu_edit, 0, 1, 1, 1)
        self.sample_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.sample_edit.setStyleSheet("QLineEdit {\n"
"    font: 10pt \"Times New Roman\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.sample_edit.setObjectName("sample_edit")
        self.timegroup_grid.addWidget(self.sample_edit, 1, 1, 1, 1)
        self.init_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.init_edit.setStyleSheet("QLineEdit {\n"
"    font: 10pt \"Times New Roman\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.init_edit.setObjectName("init_edit")
        self.timegroup_grid.addWidget(self.init_edit, 2, 1, 1, 1)
        self.state_group = QtWidgets.QGroupBox(self.para_group)
        self.state_group.setGeometry(QtCore.QRect(280, 20, 261, 161))
        self.state_group.setTitle("")
        self.state_group.setObjectName("state_group")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.state_group)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 0, 241, 161))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.stategroup_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.stategroup_grid.setContentsMargins(0, 0, 0, 0)
        self.stategroup_grid.setObjectName("stategroup_grid")
        self.process_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.process_edit.setStyleSheet("QLineEdit {\n"
"    font: 10pt \"Times New Roman\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.process_edit.setObjectName("process_edit")
        self.stategroup_grid.addWidget(self.process_edit, 0, 1, 1, 1)
        self.P_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.P_edit.setStyleSheet("QLineEdit {\n"
"    font: 10pt \"Times New Roman\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.P_edit.setObjectName("P_edit")
        self.stategroup_grid.addWidget(self.P_edit, 2, 1, 1, 1)
        self.measure_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.measure_edit.setStyleSheet("QLineEdit {\n"
"    font: 10pt \"Times New Roman\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.measure_edit.setObjectName("measure_edit")
        self.stategroup_grid.addWidget(self.measure_edit, 1, 1, 1, 1)
        self.process_lab = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.process_lab.setObjectName("process_lab")
        self.stategroup_grid.addWidget(self.process_lab, 0, 0, 1, 1)
        self.measure_lab = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.measure_lab.setObjectName("measure_lab")
        self.stategroup_grid.addWidget(self.measure_lab, 1, 0, 1, 1)
        self.P_lab = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.P_lab.setObjectName("P_lab")
        self.stategroup_grid.addWidget(self.P_lab, 2, 0, 1, 1)
        self.info_lab = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.info_lab.setObjectName("info_lab")
        self.stategroup_grid.addWidget(self.info_lab, 3, 0, 1, 1)
        self.info_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.info_edit.setStyleSheet("QLineEdit {\n"
"    font: 10pt \"Times New Roman\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.info_edit.setObjectName("info_edit")
        self.stategroup_grid.addWidget(self.info_edit, 3, 1, 1, 1)
        self.eq1_group = QtWidgets.QGroupBox(self.para_group)
        self.eq1_group.setGeometry(QtCore.QRect(10, 190, 261, 161))
        self.eq1_group.setTitle("")
        self.eq1_group.setObjectName("eq1_group")
        self.eq1_disp = QtWidgets.QGraphicsView(self.eq1_group)
        self.eq1_disp.setGeometry(QtCore.QRect(0, 0, 261, 161))
        self.eq1_disp.setObjectName("eq1_disp")
        self.eq2_group = QtWidgets.QGroupBox(self.para_group)
        self.eq2_group.setGeometry(QtCore.QRect(280, 190, 261, 161))
        self.eq2_group.setTitle("")
        self.eq2_group.setObjectName("eq2_group")
        self.eq2_disp = QtWidgets.QGraphicsView(self.eq2_group)
        self.eq2_disp.setGeometry(QtCore.QRect(0, 0, 261, 161))
        self.eq2_disp.setObjectName("eq2_disp")
        self.title_lab = QtWidgets.QLabel(self.centralwidget)
        self.title_lab.setGeometry(QtCore.QRect(10, 10, 551, 61))
        self.title_lab.setStyleSheet("QLabel {\n"
"    font: 28pt \"华文中宋\";\n"
"    qproperty-alignment: AlignCenter;  /* 文字居中 */\n"
"}\n"
"")
        self.title_lab.setObjectName("title_lab")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 566, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.simu_btn.setText(_translate("MainWindow", "进行仿真"))
        self.exit_btn.setText(_translate("MainWindow", "退出"))
        self.save_data_box.setText(_translate("MainWindow", "保存数据"))
        self.yes_btn.setText(_translate("MainWindow", "Yes"))
        self.no_btn.setText(_translate("MainWindow", "No"))
        self.method_menu.setItemText(0, _translate("MainWindow", "请选择滤波方式"))
        self.method_menu.setItemText(1, _translate("MainWindow", "信息滤波"))
        self.method_menu.setItemText(2, _translate("MainWindow", "UD滤波"))
        self.method_menu.setItemText(3, _translate("MainWindow", "遗忘滤波"))
        self.method_menu.setItemText(4, _translate("MainWindow", "自适应遗忘滤波(1)"))
        self.method_menu.setItemText(5, _translate("MainWindow", "自适应遗忘滤波(2)"))
        self.save_fig_box.setText(_translate("MainWindow", "保存图片"))
        self.save_time_lab.setText(_translate("MainWindow", "保存数据是否记录当前时间"))
        self.para_group.setTitle(_translate("MainWindow", "参数设置"))
        self.sample_lab.setText(_translate("MainWindow", "采样时长"))
        self.simu_lab.setText(_translate("MainWindow", "仿真时长"))
        self.init_lab.setText(_translate("MainWindow", "初始状态"))
        self.simu_edit.setText(_translate("MainWindow", "300"))
        self.sample_edit.setText(_translate("MainWindow", "1"))
        self.init_edit.setText(_translate("MainWindow", "[10000;-300]"))
        self.process_edit.setText(_translate("MainWindow", "0.5"))
        self.P_edit.setText(_translate("MainWindow", "[100,1]"))
        self.measure_edit.setText(_translate("MainWindow", "2500"))
        self.process_lab.setText(_translate("MainWindow", "过程噪声"))
        self.measure_lab.setText(_translate("MainWindow", "量测噪声"))
        self.P_lab.setText(_translate("MainWindow", "协方差"))
        self.info_lab.setText(_translate("MainWindow", "信息矩阵"))
        self.info_edit.setText(_translate("MainWindow", "[0,0;0,0]"))
        self.title_lab.setText(_translate("MainWindow", "卡尔曼滤波仿真软件Demo"))
